
# Entity Test Entities descriptor (FAKE)

fields:
    # Header
    create_date:            datetime=sqlDatetime()
    create_ip:              ip=clientIP()
    create_user_id:         ref=userID()
    
    name: string(4, 20)

indexes:
     - UNIQUE(name)
     