# 
# Usage:
# Route Access Type > Route > Route Config
# 
# This YAML configuration file is made to work with package orpheus/orpheus-inputcontroller
# 
# HTTP Route allows the following config:
# - path : The relative path to this route. Mandatory config.
# - method : Restrict path access to the given HTTP method.
# - controller : The controller to use to process this route
# - restrictTo : Restriction configuration for this route, you can customize accessibility, the common field is "role".
# - redirect : Redirect to the given URL, using RedirectController.
# - url_config : Redirect to the URL provided by the configurable url_config, using RedirectController & AppConfig. Require orpheus/orpheus-webtools.
# - render : The template to render this route, using StaticPageController. Processed as option.
# Other fields will be sent as options to the controller, controller can access to all this configuration.
#
# Known roles: visitor, member, moderator, administrator, developer
# Unspecified role does not restrict access, "visitor" restricts to not-logged user only.
#
# Examples :
#    home:
#        path: "/path/in/array/config"
#        method: "POST|GET"
#        method: "GET"
#        controller: App\Controller\HomeController
#    home2: "/path/with/all/methods->HomeController"
#    home3: "POST(/path/for/POST/method)->HomeController"

http:
    home:
        path: "/"
        controller: App\Controller\HomeController
        
#    user_login:
#        path: "/user/signin.html"
#        controller: App\Controller\UserLoginController
#        restrictTo:
#          role: visitor
#
#    logout:
#        path: "/logout.html"
#        controller: App\Controller\LogoutController
#        restrictTo:
#          role: member
#
#    admin_demo:
#        path: "/admin/home.html"
#        controller: App\Controller\Admin\AdminDemoController
#        restrictTo:
#          role: member
#
#    adm_mysettings:
#        path: "/admin/my_settings.html"
#        controller: App\Controller\Admin\AdminMySettingsController
#        restrictTo:
#          role: member
#
#    adm_users:
#        path: "/admin/users.html"
#        controller: App\Controller\Admin\AdminUserListController
#        restrictTo:
#          role: administrator
#
#    adm_user:
#        path: "/admin/user/{id:userID}.html"
#        controller: App\Controller\Admin\AdminUserEditController
#        restrictTo:
#          role: administrator
#
#    file_download:
#        path: "/download/{id:fileID}"
#        controller: App\Controller\FileDownloadController
#
#
#    # Dev Area
#
#    dev_home:
#        path: "/developer/home.html"
#        controller: App\Controller\Developer\DevHomeController
#        restrictTo:
#            role: developer
#
#    dev_system:
#        path: "/developer/system.html"
#        controller: App\Controller\Developer\DevSystemController
#        restrictTo:
#            role: developer
#
#    dev_phpinfo:
#        path: "/developer/phpinfo.html"
#        controller: App\Controller\Developer\DevPhpInfoController
#        restrictTo:
#            role: developer
#
#    dev_composer:
#        path: "/developer/composer.html"
#        controller: App\Controller\Developer\DevComposerController
#
#    dev_entities:
#        path: "/developer/entities.html"
#        controller: App\Controller\Developer\DevEntitiesController
#        restrictTo:
#          role: developer
#
#    dev_loglist:
#        path: "/developer/logs.html"
#        controller: App\Controller\Developer\DevLogListController
#        restrictTo:
#          role: developer
#
#    dev_log_view:
#        path: "/developer/view_log.html"
#        controller: App\Controller\Developer\DevLogViewController
#        restrictTo:
#          role: developer
#
#    dev_app_translate:
#        path: "/developer/translate_application.html"
#        controller: App\Controller\Developer\DevAppTranslateController
#        restrictTo:
#          role: developer
#
#    dev_config:
#        path: "/developer/config.html"
#        controller: App\Controller\Developer\DevConfigController
#        restrictTo:
#          role: developer
    
    
    # Setup
    
#    setup_start:
#        path: "/setup/"
#        controller: App\Controller\Setup\StartSetupController
#
#    setup_checkfs:
#        path: "/setup/check-filesystem.html"
#        controller: App\Controller\Setup\CheckFileSystemSetupController
#
#    setup_checkdb:
#        path: "/setup/check-database.html"
#        controller: App\Controller\Setup\CheckDatabaseSetupController
#
#    setup_installdb:
#        path: "/setup/install-database.html"
#        controller: App\Controller\Setup\InstallDatabaseSetupController
#
#    setup_installfixtures:
#        path: "/setup/install-fixtures.html"
#        controller: App\Controller\Setup\InstallFixturesSetupController
#
#    setup_end:
#        path: "/setup/finish.html"
#        controller: App\Controller\Setup\EndSetupController
